### ISSUE TITLE
Wrong values being shown?

### ISSUE THREAD

**Issue by nvirm** [josecastroleon/pimatic-openweather#26] opened 2015-11-24 21:40 UTC
Hi! I have recently started seeing a trend that the values don't always correspond on Pimatic, when compared to actual openweathermap.org site.

![Image of Pimatic](http://lurks.kapsi.fi/filut/1.PNG)
![Image of Openweather](http://lurks.kapsi.fi/filut/2.PNG)

Device:
{
      "id": "weather",
      "class": "OpenWeatherDevice",
      "name": "Helsinki tänään",
      "location": "Helsinki, FI",
      "units": "metric",
      "lang": "fi",
      "timeout": 300000
},

EDIT: Seems like sometimes the API itself isn't reliable, I have gotten both 6,9Celsius and 4Celsius (which is correct) during this hour, multiple times.

**Comment by mwittig** [comment] 2015-11-24 22:41
The values you get on the web site may be more up-to-date then what you get via the API on the "Free" service plan. The "Free" service plan will give you updated values every 1-2 hours. Unfortunately, the "Developer" plan which will give frequent updates every 10 minutes is rather expensive. See also http://openweathermap.org/price

I will make a note about this as part of the README. I am closing the issue now. Please re-open if you think the issue is caused by some other problem or the answer given is incomplete.

**Closed as completed by mwittig** 2015-11-24 22:41 UTC
